name: Build Project on Multiple Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Ïëàòôîðìû äëÿ ñáîðêè
        dotnet-version: '4.8'  # Убедитесь, что .NET Framework 4.8 доступен  Âåðñèè .NET SDK (åñëè ïðèìåíèìî)

    steps:
      # Øàã 1: Ïðîâåðêà èñõîäíîãî êîäà
      - name: Checkout code
        uses: actions/checkout@v3

      # Øàã 2: Óñòàíîâêà .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Øàã 3: Âîññòàíîâëåíèå çàâèñèìîñòåé
      - name: Restore dependencies
        run: dotnet restore

      # Øàã 4: Êîìïèëÿöèÿ ïðîåêòà
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Øàã 5: Ïðîâåðêà óñïåøíîé ñáîðêè
      - name: Verify Build Output
        run: |
          echo "Build succeeded on ${{ matrix.os }} with .NET ${{ matrix.dotnet-version }}"
