name: Build and Test .NET Framework 4.8 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Используем Windows Runner для поддержки .NET Framework

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install .NET Framework 4.8 Developer Pack
        run: |
          # Скачиваем и устанавливаем .NET Framework 4.8 Developer Pack
          Invoke-WebRequest -Uri https://aka.ms/msbuild/developerpacks/4.8/ -OutFile dotnet-framework-4.8-installer.exe
          Start-Process -Wait -FilePath dotnet-framework-4.8-installer.exe

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 4.8  # Устанавливаем .NET SDK 4.8

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release
