name: Build and Test .NET Framework 4.8 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Используем Windows Runner для поддержки .NET Framework

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET Framework 4.8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 4.8  # Устанавливаем .NET Framework SDK

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release
